# Generated by Django 3.0.5 on 2020-04-22 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.CharField(max_length=256)),
                ('imagen', models.CharField(max_length=128)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='hamburgers', to='apiapp.Ingredient')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
